# Generated by Django 4.2 on 2025-05-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_city_video_url_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['id']},
        ),
    ]
